# NAVA Demo Outputs

This folder contains anonymized sample files generated during NAVA validation tests.

These files are provided only as public demonstration outputs. They show NAVA’s ability to create office documents, Excel spreadsheets, PDF files and workflow results from natural language instructions.

The files in this folder do not contain the NAVA source code, internal engine, routing logic, memory, logs or private automation mechanisms.

## Included examples

- Word documents generated by NAVA
- PDF files exported or produced during tests
- Excel spreadsheets created during workflow validation
- Sample business documents
- Sample multi-application workflow outputs

## Important note

Only anonymized and non-sensitive files should be stored here.

Do not upload:
- source code
- screenshots showing PyCharm or internal logs
- private emails
- real client data
- local configuration files
- memory databases
- personal or confidential documents

---

# Sorties de démonstration NAVA

Ce dossier contient des fichiers d’exemple anonymisés générés pendant les tests de validation de NAVA.

Ces fichiers sont fournis uniquement comme sorties publiques de démonstration. Ils montrent la capacité de NAVA à créer des documents bureautiques, des tableaux Excel, des fichiers PDF et des résultats de workflows à partir d’instructions naturelles.

Les fichiers présents dans ce dossier ne contiennent pas le code source de NAVA, le moteur interne, la logique de routage, la mémoire, les logs ou les mécanismes privés d’automatisation.

## Exemples inclus

- Documents Word générés par NAVA
- Fichiers PDF produits ou exportés pendant les tests
- Tableaux Excel créés pendant la validation des workflows
- Documents métiers d’exemple
- Sorties de workflows multi-applications

## Note importante

Seuls les fichiers anonymisés et non sensibles doivent être stockés ici.

Ne pas uploader :
- code source
- captures montrant PyCharm ou les logs internes
- emails privés
- données client réelles
- fichiers de configuration locale
- bases de données mémoire
- documents personnels ou confidentiels
